(define (make-account balance password)
  (define (withdraw amount)
	(if (>= balance amount)
		(begin (set! balance (- balance amount))
			   balance)
		"Insufficient funds"))
  (define (deposit amount)
	(set! balance (+ balance amount))
	balance)
  (define (check-passw passw oper)
	(lambda (amount)
	  (if (eq? password passw)
		  (oper amount)
		  "Incorrect password")))
  (define (dispatch passw oper)
	(cond ((eq? oper 'withdraw) (check-passw passw withdraw))
		  ((eq? oper 'deposit) (check-passw passw deposit))
		  (else (error "Unknown operation -- MAKE-ACCOUNT"
					   oper))))
  dispatch)
