(define (make-account balance password)
  (define max-incorrect-allowed 7)
  (define (withdraw amount)
	(if (>= balance amount)
		(begin (set! balance (- balance amount))
			   balance)
		"Insufficient funds"))
  (define (deposit amount)
	(set! balance (+ balance amount))
	balance)
  (define (check-passw passw oper)
	(lambda (amount)
	  (if (eq? password passw)
		  (oper amount)
		  (incorrect-password-action))))
  (define (incorrect-password-action)
	(if (> max-incorrect-allowed 0)
		(begin (set! max-incorrect-allowed (- max-incorrect-allowed 1))
			   "Incorrect password")
		"Calling the police!"))
  (define (dispatch passw oper)
	(cond ((eq? oper 'withdraw) (check-passw passw withdraw))
		  ((eq? oper 'deposit) (check-passw passw deposit))
		  (else (error "Unknown operation -- MAKE-ACCOUNT"
					   oper))))
  dispatch)
