(define (make-account balance password)
  (define (withdraw amount)
	(if (>= balance amount)
		(begin (set! balance (- balance amount))
			   balance)
		"Insufficient funds"))
  (define (deposit amount)
	(set! balance (+ balance amount))
	balance)
  (define (check-passw passw oper)
	(lambda (amount)
	  (if (eq? password passw)
		  (oper amount)
		  "Incorrect password")))
  (define (dispatch passw oper)
	(cond ((eq? oper 'withdraw) (check-passw passw withdraw))
		  ((eq? oper 'deposit) (check-passw passw deposit))
		  (else (error "Unknown operation -- MAKE-ACCOUNT"
					   oper))))
  dispatch)

(define (make-joint original-account original-account-password password)
  (define (check-passw passw oper)
	(lambda (amount)
	  (if (eq? password passw)
		  ((original-account original-account-password oper) amount)
		  "Incorrect password")))
  check-passw)

(define peter-acc (make-account 100 'secret1))
(define paul-acc
  (make-joint peter-acc 'secret1 'secret2))
