(load "ch03/constraint.scm")
(load "test-manager/load.scm")

(define (celsius-fahrenheit-converter c f)
  (let ((u (make-connector))
		(v (make-connector))
		(w (make-connector))
		(x (make-connector))
		(y (make-connector)))
	(multiplier c w u)
	(multiplier v x u)
	(adder v y f)
	(constant 9 w)
	(constant 5 x)
	(constant 32 y)
	'ok))

(in-test-group
 cf-tests

 (define-test (cf-forward-test)
   (define C (make-connector))
   (define F (make-connector))
   (celsius-fahrenheit-converter C F)
   (set-value! C 25 'user)
   (assert-equal 77 (get-value F)))

 (define-test (cf-backward-test)
   (define C (make-connector))
   (define F (make-connector))
   (celsius-fahrenheit-converter C F)
   (set-value! F 212 'user)
   (assert-equal 100 (get-value C)))
)
(run-test '(cf-tests))
